[package]
name = "pci"
version = "0.1.0"
authors = ["Andrei Răduță <andrei.raduta11@gmail.com>"]

[dependencies]
devices = { path = "../devices" }
polly = { path = "../polly" }
utils = { path = "../utils" }
